#================================================================================================================
swagger: "2.0"

info:
  version: "1.0.0"
  title: Juliye API Online
  description: "The brand new online API service with new router、authenticating、versioning etc."

# during dev, should point to your local machine
# TODO: chg sub domain
#   api.juliye.com
#   api-test.juliye.com
host: wx-test.zlycare.com # localhost:10010 #

# basePath prefixes all resource paths
# TODO: version 1
basePath: /1

# The transfer protocol of the API.
schemes:
  # tip: remove http to make production-grade
  - http
  # - https # TODO: support https
  # - ws
  # - wss

# format of bodies a client can send (Content-Type)
# global, can be overridden on special api calls
consumes:
  - application/json

# format of the responses to the client (Accepts)
# global, can be overridden on special api calls
produces:
  - application/json

#================================================================================================================
# The available paths and operations for the API
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /indexes/regions:
    x-swagger-router-controller: Indexes
    get:
      description: 获取省市地区列表
      operationId: getRegions
      parameters:
        - name: name
          in: query
          description: 地名 (模糊搜索)
          required: false
          type: string
        - name: areaId
          in: query
          description: 地区ID
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/RegionEntity"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


#================================================================================================================
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  RegionEntity:
    required:
      - _id
      - name
      - updatedAt
      - createdAt
    properties:
      _id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
      createdAt:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
