#================================================================================================================
swagger: "2.0"

info:
  version: "1.0.0"
  title: Juliye API Online
  description: "The brand new online API service with new router、authenticating、versioning etc."

# during dev, should point to your local machine
# TODO: chg sub domain
#   api.juliye.com
#   api-test.juliye.com
host: localhost:8180 # api.juliye.com # localhost:10010 #

# basePath prefixes all resource paths
# TODO: version 1
basePath: /3

# The transfer protocol of the API.
schemes:
  # tip: remove http to make production-grade
  - http
  # - https # TODO: support https
  # - ws
  # - wss

# format of bodies a client can send (Content-Type)
# global, can be overridden on special api calls
consumes:
  - application/json

# format of the responses to the client (Accepts)
# global, can be overridden on special api calls
produces:
  - application/json

#================================================================================================================
# The available paths and operations for the API
paths:
  /sessions/account:
    x-swagger-router-controller: fake
    get:
      description: 返回当前登陆的账户信息
      operationId: NO_10003
      parameters:
        - in: header
          name: authorization
          description: jwt
          required: true
          type: string      
      responses:
        "200":
          description: 账户信息
          schema:
            $ref: "#/definitions/AccountInfo"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sessions/loginc:
    x-swagger-router-controller: fake
    post:
      description: Login
      operationId: NO_10001
      parameters:
        - in: body
          name: body
          description: 登陆信息
          required: true
          schema: 
            $ref: "#/definitions/AuthInfo"
      responses:
        "200":
          description: 登陆成功,返回User info and token
          schema:
            $ref: "#/definitions/AccountInfo"
        default:
          description: 登陆失败,返回Error info
          schema:
            $ref: "#/definitions/ErrorResponse"            
  /sessions/logind:
    x-swagger-router-controller: fake
    post:
      description: 医生账户登陆
      operationId: NO_10002
      parameters:
        - in: body
          name: body
          description: 登陆信息
          required: true
          schema: 
            $ref: "#/definitions/AuthInfo"
      responses:
        "200":
          description: 登陆成功,返回User info and token
          schema:
            $ref: "#/definitions/AccountInfo"
        default:
          description: 登陆失败,返回Error info
          schema:
            $ref: "#/definitions/ErrorResponse"     
  /swagger:
    x-swagger-pipe: swagger_raw
#================================================================================================================
# security
# securityDefinitions:
#   api_key:
#     type: apiKey
#     name: Authentication
#     description: JWT(Json Web Token)
#     in: header
# complex objects have schema definitions
definitions:
  AccountInfo:
    required:
      - username
      - roles
    properties:
      username:
        type: string
      roles:
        type: array
        items:
          type: string
  AuthInfo:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  ErrorResponse:
    required:
      - info
    properties:
      info:
        type: string
